### ISSUE TITLE
 Move away from Github?

### ISSUE THREAD

**Issue by arnowelzel** [arnowelzel/lightbox-photoswipe#1]
Github will soon be a part of Microsoft and I'm not sure yet, if this is really the direction I want to go.

Therefore I will propably move with all my repositories away from Github. Stay tuned - I'll tell you more details here soon.

**Comment by cweiske** [comment]
What are your reasons for staying here?

**Comment by arnowelzel** [comment]
First of all - there are so many projects where I am involved which still are on Github and not very likely to move another platform.

Second - even if Github might ever change in a way that I don't like it any more, I still have all my repositories on my local computer anway and can easily transfer them to Gitlab or any other provider or even run my own Git server to share repositories with others.

And finally - so far Github did not become worse, so I don't see any reason to leave it right now. I also don't believe in decisions solely driven by emotions or ideology.

**Comment by cweiske** [comment]
Thanks for the explanation.
