### ISSUE TITLE
Document changes to "stock" PhotoSwipe / differences between skins

### ISSUE THREAD

**Issue by jefferyto** [arnowelzel/lightbox-photoswipe#2]
First, thanks for creating this plugin :smile:

I was comparing the PhotoSwipe js/css bundled with this plugin and those from "stock" PhotoSwipe, and I noticed that you had made some changes. I think it would nice to document these changes somewhere (maybe in the readme) so that users can know what to expect.

Also, I see that there are four skin options; I think it would be nice again to document the differences between these options (and any changes from the "stock" PhotoSwipe default skin), so that users don't need to try each one to figure out which one to use.

Thanks again!

**Comment by arnowelzel** [comment]
Thanks for the suggestion.

I'll add a documentation about the differences in the future. Most of the changes are there to deal with specific WordPress skins and their CSS rules. There are also some little tweaks in the code, not only in the CSS rules.

However, it seems that the "stock" PhotoSwipe 4 will not updates any longer (see https://github.com/dimsemenov/PhotoSwipe - the last commit is 11 months ago and there are 59 open pull requests). I also created pull request for of my changes a while ago, but they did not get merged yet:

https://github.com/dimsemenov/PhotoSwipe/pull/1455

**Comment by arnowelzel** [comment]
Closed with 57db26c72ba2c0ba7cd0ce365e211e2764a8ee77
