### ISSUE TITLE
Missing alt tag in lightbox img

### ISSUE THREAD

**Issue by C0pyR1ght** [arnowelzel/lightbox-photoswipe#21]
Hi Arno,

I appreciate the hard work you put into this and the frequent updates you provide. 
We are currently putting some effort in SEO-optimizing our site. In the course of that we discovered a missing alt-tag for the image that opens inside the lightbox even though the alt-tag on the original image is set.

`<img class="pswp__img" src="/path/to/img.jpg" style="display: block; width: 473px; height: 473px;">`

**Comment by arnowelzel** [comment]
Thanks for pointing this out. I'll fix this for the next update.

**Comment by arnowelzel** [comment]
Fixed with 7d1cac173393a5c8da2c4475b6ffb176150f837c

Just a note: since the images in the lightbox are only created dynamically when opening it no search engine will ever see this.

**Comment by C0pyR1ght** [comment]
great, thanks for the quick reply

> Just a note: since the images in the lightbox are only created dynamically when opening it no search engine will ever see this.

didn't knew that. But that explains why lighthouse audit didn't point this out.
