### ISSUE TITLE
[Feature Request] Add loading lazy attribute to the thumbnail image

### ISSUE THREAD

**Issue by mtoensing** [arnowelzel/lightbox-photoswipe#41]
I would like to propose a feature request to your great plugin. The images in the post are currently loaded as img tags:

```
<li class="blocks-gallery-item">
    <figure>
        <a href="full.jpg" data-lbwps-width="1920" data-lbwps-height="1080">
            <img
                src="thumbnails.jpg"
                alt=""
                data-id="36724"
                data-full-url="full.jpg"
                data-link="/?attachment_id=36724"
                class="wp-image-36724"
                srcset="260x113.jpeg 260w, 460x200.jpeg 460w, 920x400.jpeg 920w"
                sizes="(max-width: 260px) 100vw, 260px"
                loading="lazy"
            />
        </a>
    </figure>
</li>
```

My proposal would be to simply add the new native lazy loading attribute to the thumbnail image: 

```
<li class="blocks-gallery-item">
    <figure>
        <a href="full.jpg" data-lbwps-width="1920" data-lbwps-height="1080">
            <img
                src="thumbnails.jpg"
                alt=""
                data-id="36724"
                data-full-url="full.jpg"
                data-link="/?attachment_id=36724"
                class="wp-image-36724"
                srcset="260x113.jpeg 260w, 460x200.jpeg 460w, 920x400.jpeg 920w"
                sizes="(max-width: 260px) 100vw, 260px"
                loading="lazy"
            />
        </a>
    </figure>
</li>
```
It is already supported in Chrome. I would not integrate a js script to lazy load anymore. To much ovberhead. And this sounds like a simple addition. This would help center pages like this: https://marc.tv/bildergalerien/

**Comment by arnowelzel** [comment]
This already implemented. Just set the option "Add native lazy loading to images" in the backend settings. This is not set be default, because in some cases it causes conflicts with existing themes or other plugins.

See in action here: https://arnowelzel.de/en/england-2017

If that does not work in your site, than I have to do further debugging.

**Comment by mtoensing** [comment]
No it works. I just did not see that in the settings.
