### ISSUE TITLE
Add check for "SCRIPT_DEBUG" wp const?

### ISSUE THREAD

**Issue by hristov296** [arnowelzel/lightbox-photoswipe#61]
What do you think about adding a check for the 'SCRIPT_DEBUG" const? That way, if someone wants to examine your js to find out how something works, they can just define the SCRIPT_DEBUG = true and load the unminified version on the website. I was using it on one of my plugins, I can make a PR if you want to see an example

**Comment by hristov296** [comment]
https://wordpress.org/support/article/debugging-in-wordpress/#script_debug
Here is info on `SCRIPT_DEBUG`

**Comment by arnowelzel** [comment]
Yes, this makes sense. A pull request is welcome, thanks.

**Comment by arnowelzel** [comment]
Closed with  #62
