### ISSUE TITLE
Display only a single image from a gallery in Lightbox

### ISSUE THREAD

**Issue by matthiasballreich** [arnowelzel/lightbox-photoswipe#77]
I' using the CoBlock-Plugin and create with that my image galleries. But by default when i open one image withe your plugin i have the option to navigate to the other images inside the lightbox. I think an option for diabling that would be nice, too, so that only the selected / clicked image will be loaded and no navigation will be possible.

**Comment by arnowelzel** [comment]
This looks like a duplicate of #71.

**Comment by matthiasballreich** [comment]
you're right. i've missed this
