### ISSUE TITLE
PHP Warning:  extract() expects parameter 1 to be array, bool given

### ISSUE THREAD

**Issue by aharonach** [arnowelzel/lightbox-photoswipe#86]
Hello there,

I'm getting lots of PHP warnings as follows:
`PHP Warning:  extract() expects parameter 1 to be array, bool given in /public_html/wp-content/plugins/lightbox-photoswipe/lightbox-photoswipe.php on line 685`

Since not all my images on the website are hosted locally, some of them are from external servers, so my server redirects the request to the external server. Your plugin tries to get some info of the image and it fails because of the reason I've written here.

The problematic line is `extract( $imgDetails );`.
The solution should be to set an initial value to that variable at the beginning of the method, something like: `$imgDetails = array();`.

Hope you'll fix that soon! 😄

**Comment by aharonach** [comment]
Hi again,
just noticed that it was fixed in the last version.
Thank you very much!

**Comment by arnowelzel** [comment]
Yes - this bug was introduced when refactoring the backend code and I already have seen this just after publishing the update. Sorry for the confusion.
