### ISSUE TITLE
Wrong path usage with `get_home_url`

### ISSUE THREAD

**Issue by herrvigg** [arnowelzel/lightbox-photoswipe#98]
See code here:
https://github.com/arnowelzel/lightbox-photoswipe/blob/3fde62402ef03760d385003191e26346fc0feaf2/src/LightboxPhotoSwipe/LightboxPhotoSwipe.php#L274

The second parameter passed to `get_home_url` should not be null, you should use `''` empty string instead if you want to leave it as default.
This is not compliant with the WordPress signature: https://developer.wordpress.org/reference/functions/get_home_url/.

Also, why do you call for the 'http' scheme? The default is `https`. Seems you should use the function with default parameters, that is `get_home_url()`. Please check all the calls done in a similar fashion.

Related issue detected in our qTranslate-XT plugin: https://github.com/qtranslate/qtranslate-xt/issues/1333.

**Comment by arnowelzel** [comment]
Closed with https://github.com/arnowelzel/lightbox-photoswipe/commit/9209ff1c3e2379b99fb63aeeebf2ae9e13e0dea4

**Comment by herrvigg** [comment]
Awesome, thanks! 👍

**Comment by herrvigg** [comment]
This kind of bugs is detected by stronger PHP types used in the signatures.
It would be great if WordPress add such checks, but it would be hard for them to deal with all the technical debt (many plugins would break). The best we can do is start to adding those in plugins. The transition for better a PHP state in WordPress will be long.
