### ISSUE TITLE
Error when trying to build

### ISSUE THREAD

**Issue by Kidoo96** [arnowelzel/lightbox-photoswipe#99]
Hi, I tried to add a print button but when running **php build.php** command.

I got this error 

**Parse error: syntax error, unexpected ':', expecting ';' or '{' in \lightbox-photoswipe\build.php on line 18**

**Comment by arnowelzel** [comment]
Well - that line is perfectly ok and contains a function declaration with a return type hint. The script works with PHP 7.4, 8.0 and 8.1.

What PHP version do you use? You need at least PHP 7.4 - and even that PHP version is already "end of life" (also see https://www.php.net/supported-versions.php)

**Comment by arnowelzel** [comment]
I removed the type hint, so you **may** be able to use the script even with ancient PHP versions. However it is still not recommended to use such old versions.

**Comment by Kidoo96** [comment]
Yeah my bad. PHP cli version was 5.6 just updated it on 8.0. Didn't check the cli version. Thanks for the feedback.
